let listings = JSON.parse(localStorage.getItem("listings"))
? JSON.parse(localStorage.getItem("listings")):[
    {image: 'https://picsum.photos/200/300/?blur',
    id:1,
     title:'Light and Modern Apartment',
     price: '$4500/mo',
     address:'2436 SW 8th St, Miami, FL 33135, USA',
     bedrooms:'4',
     bathrooms:'2',
     garage:'1',
     size:'1200',
     type:'Apartment',
     user:' Samuel Palmer',
     datePosted:'04/04/2020',
     yearBuilt:'2016',
    },
    {image:'https://picsum.photos/200/300/?blur',
    id:2,
    title:'Cute Apartment',
    price: '$4500/mo',
    address:'2436 SW 8th St, Miami, FL 33135, USA',
    bedrooms:'4',
    bathrooms:'2',
    garage:'1',
    size:'1200',
    type:'Apartment',
    user:' Samuel Palmer',
    datePosted:'04/04/2020',
    yearBuilt:'2016',
   },
   {image: 'https://picsum.photos/200/300/?blur',
   id:3,
   title:'Cozy Apartment',
   price: '$4500/mo',
   address:'2436 SW 8th St, Miami, FL 33135, USA',
   bedrooms:'4',
   bathrooms:'2',
   garage:'1',
   size:'1200',
   type:'Apartment',
   user:' Samuel Palmer',
   datePosted:'04/04/2020',
   yearBuilt:'2016',
  },
  {image: 'https://picsum.photos/200/300/?blur',
  id:4,
  title:'Newly Built Apartment',
  price: '$4500/mo',
  address:'2436 SW 8th St, Miami, FL 33135, USA',
  bedrooms:'4',
  bathrooms:'2',
  garage:'1',
  size:'1200',
  type:'Apartment',
  user:' Samuel Palmer',
  datePosted:'04/04/2020',
  yearBuilt:'2016',
 },
 {image: 'https://picsum.photos/200/300/?blur',
     id:5,
 title:'Fully Furnished Apartment',
 price: '$4500/mo',
 address:'2436 SW 8th St, Miami, FL 33135, USA',
 bedrooms:'4',
 bathrooms:'2',
 garage:'1',
 size:'1200',
 type:'Apartment',
 user:' Samuel Palmer',
 datePosted:'04/04/2020',
 yearBuilt:'2016',
},
{image: 'https://picsum.photos/200/300/?blur',
    id:6,
     title:'North Facing listing',
     price: '$4500/mo',
     address:'2436 SW 8th St, Miami, FL 33135, USA',
     bedrooms:'4',
     bathrooms:'2',
     garage:'1',
     size:'1200',
     type:'Apartment',
     user:' Samuel Palmer',
     datePosted:'04/04/2020',
     yearBuilt:'2016',
    },
    {image: 'https://picsum.photos/200/300/?blur',
        id:7,
    title:'Newly Built listing',
    price: '$4500/mo',
    address:'2436 SW 8th St, Miami, FL 33135, USA',
    bedrooms:'4',
    bathrooms:'2',
    garage:'1',
    size:'1200',
    type:'Apartment',
    user:' Samuel Palmer',
    datePosted:'04/04/2020',
    yearBuilt:'2016',
   },
   {image: 'https://picsum.photos/200/300/?blur',
       id:8,
   title:'Grand Mansion',
   price: '$4500/mo',
   address:'2436 SW 8th St, Miami, FL 33135, USA',
   bedrooms:'4',
   bathrooms:'2',
   garage:'1',
   size:'1200',
   type:'Apartment',
   user:' Samuel Palmer',
   datePosted:'04/04/2020',
   yearBuilt:'2016',
  },
  {image: 'https://picsum.photos/200/300/?blur',
  id:9,
  title:'Bachelor Pad',
  price: '$4500/mo',
  address:'2436 SW 8th St, Miami, FL 33135, USA',
  bedrooms:'4',
  bathrooms:'2',
  garage:'1',
  size:'1200',
  type:'Apartment',
  user:' Samuel Palmer',
  datePosted:'04/04/2020',
  yearBuilt:'2016',
 },
 {image: 'https://picsum.photos/200/300/?blur',
 id:10,
 title:'Pentlisting Open Floor',
 price: '$4500/mo',
 address:'2436 SW 8th St, Miami, FL 33135, USA',
 bedrooms:'4',
 bathrooms:'2',
 garage:'1',
 size:'1200',
 type:'Apartment',
 user:' Samuel Palmer',
 datePosted:'04/04/2020',
 yearBuilt:'2016',
},]
   const propertiesContainer = document.querySelector("#properties")
// add array to local storage
//    localStorage.setItem("listings", JSON.stringify(listings));
// display local storage
// document.getElementById("properties").innerHTML = JSON.parse( localStorage.getItem("listings"));
function showlistings (listings) {
    propertiesContainer.innerHTML = "";
    listings.forEach(listing => {
        propertiesContainer.innerHTML += `
      
        </section>
            <div id='listingcards'>
                <img src=${ listing.image } />
                 <h3>${listing.title}</h3>
                 <p>${listing.address}</p>
                 <ul id=listing-values>
                 <li><i class="fa-solid fa-bed"></i>${listing.bedrooms}</li>
                 <li><i class="fa-solid fa-shower"></i>${listing.bathrooms}</li>
                <li><i class="fa-solid fa-car"></i>${listing.garage}</li>
                <li><i class="fa-solid fa-ruler"></i>${listing.size}</li>
            </div>
        `
    })
}
showlistings(listings);